name: thredofon_repository
description: A Dart Repository which manages the thredofon domain.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.1
  sqflite: ^2.0.1


dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.1.0
  flutter_lints: ^1.0.0


